version: 1
disable_existing_loggers: false

formatters:
  devlog:
    format: '%(levelname)-8s - %(asctime)s - %(name)s:%(module)s:%(funcName)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: devlog
    stream: ext://sys.stdout

loggers:
  devlog:
    handlers:
      - console
    propagate: false
    level: DEBUG

root:
  handlers:
    - console
  level: INFO
